[package]
name = "async_task_example"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
sugars_async_task = { path = "../../packages/async_task" }
sugars_collections = { path = "../../packages/collections" }
