[package]
name = "cyrup_sugars"
version = "0.2.0"
edition = "2021"
authors = ["David Maple <david@cyrup.ai>"]
description = "Main crate providing syntactic sugar and utilities for Rust development"
homepage = "https://github.com/cyrup-ai/cyrup-sugars"
repository = "https://github.com/cyrup-ai/cyrup-sugars"
documentation = "https://docs.rs/cyrup_sugars"
license = "MIT OR Apache-2.0"
keywords = ["rust", "utilities", "collections", "async", "cyrup"]
categories = ["development-tools", "data-structures"]
readme = "../../README.md"

[lib]
name = "cyrup_sugars"
path = "src/lib.rs"

[features]
default = ["tokio-async"]
all = ["tokio-async", "std-async", "crossbeam-async", "array-tuples"]
tokio-async = ["tokio", "futures", "parking_lot", "sugars_async_task/tokio", "sugars_async_stream/tokio-backend"]
std-async = ["futures", "async-channel", "sugars_async_stream/std-backend"]
crossbeam-async = ["crossbeam", "futures", "async-channel", "sugars_async_stream/crossbeam-backend"]
array-tuples = ["sugars_collections/array-tuples"]

[dependencies]
sugars_collections = { path = "../collections" }
sugars_async_task = { path = "../async_task" }
sugars_async_stream = { path = "../async_stream" }
sugars_macros = { path = "../macros" }
sugars_gix = { path = "../gix" }
sugars_builders = { path = "../builders" }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
hashbrown = { version = "0.15.4", features = ["serde"], optional = true }
gix-hash = { version = "0.19.0", optional = true }
tokio = { version = "1", features = ["rt", "sync", "macros"], optional = true }
futures = { version = "0.3.31", optional = true }
parking_lot = { version = "0.12.4", optional = true }
crossbeam = { version = "0.8.4", optional = true }
async-channel = { version = "2.5.0", optional = true }
# workspace-hack = { version = "0.2.0", path = "../../workspace-hack" }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
tokio-test = "0.4.4"
criterion = "0.7"
proptest = "1.7.0"
pretty_assertions = "1.4.1"
serde_json = "1"
