[package]
name = "sugars_async_stream"
version = "0.2.0"
edition = "2021"
description = "Async stream utilities and abstractions for the cyrup-sugars ecosystem"
license = "MIT OR Apache-2.0"
authors = ["David Maple <david@cyrup.ai>"]
homepage = "https://github.com/cyrup-ai/cyrup-sugars"
repository = "https://github.com/cyrup-ai/cyrup-sugars"
documentation = "https://docs.rs/sugars_async_stream"
keywords = ["rust", "utilities", "async", "stream", "cyrup"]
categories = ["asynchronous", "development-tools"]
readme = "../../README.md"

[lib]
path = "src/lib.rs"

[dependencies]
sugars_async_task = { path = "../async_task" }
sugars_collections = { path = "../collections" }
tokio = { version = "1.46.1", features = ["rt", "sync", "macros"], optional = true }
futures = "0.3.31"
parking_lot = { version = "0.12.4", optional = true }
crossbeam = { version = "0.8.4", optional = true }
async-channel = { version = "2.5.0", optional = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[features]
default = ["tokio-backend"]
tokio-backend = ["tokio", "parking_lot"]
std-backend = ["async-channel"]
crossbeam-backend = ["crossbeam", "async-channel"]
