[package]
name = "sugars_collections"
version = "0.2.0"
edition = "2021"
description = "Efficient collection types including ZeroOneOrMany and OneOrMany with array tuple syntax support"
license = "MIT OR Apache-2.0"
authors = ["David Maple <david@cyrup.ai>"]
homepage = "https://github.com/cyrup-ai/cyrup-sugars"
repository = "https://github.com/cyrup-ai/cyrup-sugars"
documentation = "https://docs.rs/sugars_collections"
keywords = ["rust", "utilities", "collections", "async", "cyrup"]
categories = ["data-structures", "development-tools"]
readme = "../../README.md"

[lib]
path = "src/lib.rs"
name = "sugars_collections"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
hashbrown = { version = "0.15.4" }
# workspace-hack = { version = "0.2.0", path = "../../workspace-hack" }

[features]
default = []
array-tuples = []

[dev-dependencies]
pretty_assertions = "1.4.1"
