[package]
name = "sugars_gix"
version.workspace = true
edition.workspace = true
description = "Git integration utilities for the cyrup-sugars ecosystem"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/sugars_gix"
keywords = ["rust", "git", "gix", "utilities", "cyrup"]
categories = ["development-tools"]
readme = "../../README.md"

[lib]
path = "src/lib.rs"

[dependencies]
gix-hash = "0.18.0"
parking_lot = "0.12.4"
hashbrown = "0.15.4"
# workspace-hack = { version = "0.2.0", path = "../../workspace-hack" }
