[package]
name = "zero_one_or_many_example"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
sugars_collections = { path = "../../packages/collections" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hashbrown = { version = "0.15.4", features = ["serde"] }