[package]
name = "zero_one_or_many_example"
version = "0.1.0"
edition = "2021"

[dependencies]
sugars_collections = { path = "../../packages/collections" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hashbrown = { version = "0.15.4", features = ["serde"] }